20180306

diff --git a/innobackupex_script b/innobackupex_script
--- a/innobackupex_script
+++ b/innobackupex_script
@@ -46,6 +46,7 @@ fi
 do_install(){
     yum install http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm -y
     yum install percona-xtrabackup-24 -y
+    yum install qpress -y
 }
 
 
@@ -312,6 +313,21 @@ checkPidExists() {
     else
         return 0
     fi
+}
+
+do_packaging()
+{
+    LAST_DAY=$(perl -e 'use POSIX;print strftime "%Y%m%d",localtime time-86400;')
+  if test -d ${BAK_PATH}/${LAST_DAY};then
+      tar czvf ${LAST_DAY}_full_and_inc.tar.gz
+    if [ $? -eq 0 ];then
+        rm -rf ${BAK_PATH}/${LAST_DAY}
+    fi
+  else
+      echo "${BAK_PATH}/${LAST_DAY} not found"
+      :
+      # exit 1
+  fi
 }
 
 case $1 in
