20180306

diff --git a/innobackupex_script b/innobackupex_script
--- a/innobackupex_script
+++ b/innobackupex_script
@@ -318,16 +318,17 @@ checkPidExists() {
 do_packaging()
 {
     LAST_DAY=$(perl -e 'use POSIX;print strftime "%Y%m%d",localtime time-86400;')
-  if test -d ${BAK_PATH}/${LAST_DAY};then
-      tar czvf ${LAST_DAY}_full_and_inc.tar.gz
-    if [ $? -eq 0 ];then
-        rm -rf ${BAK_PATH}/${LAST_DAY}
+    if test -d ${BAK_PATH}/${LAST_DAY};then
+        cd ${BAK_PATH}
+        tar czvf ${LAST_DAY}_full_and_inc.tar.gz
+        if [ $? -eq 0 ];then
+            rm -rf ${BAK_PATH}/${LAST_DAY}
+        fi
+    else
+        echo "${BAK_PATH}/${LAST_DAY} not found"
+        :
+        # exit 1
     fi
-  else
-      echo "${BAK_PATH}/${LAST_DAY} not found"
-      :
-      # exit 1
-  fi
 }
 
 case $1 in
