20180226

diff --git a/innobackupex_script b/innobackupex_script
--- a/innobackupex_script
+++ b/innobackupex_script
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 
 # --no-timestamp:
@@ -27,7 +27,8 @@ SOCK_FILE='/data/db/mysql/var/mysql.sock'
 DATA_DIR='/data/db/mysql/var'
 BASE_DIR=${BAK_PATH}/${CURRENT_DATE}
 SCRIPT_DIR='/root/scripts'
-ADMIN_PASS='password'
+BINLOG_DIR='/data/db/mysql_binlog'
+# BINLOG_BIN='/usr/local/lnmp/mysql/bin/mysqlbinlog'
 
 
 if [ "$UID" -ne 0 ];then
@@ -41,10 +42,6 @@ else
     :
 fi
 
-if [ ! -d ${BASE_DIR} ];then
-    mkdir -p ${BASE_DIR}
-fi
-
 do_install(){
     yum install http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm -y
     yum install percona-xtrabackup-24 -y
@@ -52,6 +49,9 @@ do_install(){
 
 
 do_full_backup() {
+    if [ ! -d ${BASE_DIR} ];then
+        mkdir -p ${BASE_DIR}
+    fi
     innobackupex \
     --defaults-file=${CONF_FILE} \
     --user=${USER} \
@@ -88,7 +88,6 @@ do_read_file() {
 
 do_inc_backup(){
     LAST_BACKUP_DIR=`do_read_file`
-    echo ${LAST_BACKUP_DIR}
     if [ -z ${LAST_BACKUP_DIR} ];then
         echo "Not found last_backup_dir.data file"
         exit 1
@@ -119,7 +118,7 @@ do_inc_backup(){
 
 do_write_list(){
     if [ -d ${BAK_PATH}/$1 ]; then
-        if test -f ${BAK_PATH}/$1/list.lock;then
+        if test -f ${SCRIPT_DIR}/list.lock;then
             echo "list.lock存在" >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
             exit 1
         fi
@@ -131,53 +130,52 @@ do_write_list(){
 }
 
 do_merge_backup(){
-    recovery_time=$1
-    recovery_date=$2
-    end_line_number=$(grep -n "$recovery_time" list.lock | awk -F':' '{print $1}')
-    # echo ${end_line_number}
+    RECOVERY_INC_DIR=$1
+    SUB_BACKUP_DIR=$2
+    END_NR_NUM=$(grep -n "$RECOVERY_INC_DIR" ${SCRIPT_DIR}/list.lock | awk -F':' '{print $1}')
     if [ -f ${SCRIPT_DIR}/list.lock ];then
-        for ((counter=1; counter<=${end_line_number}; ++counter))
+        for ((counter=1; counter<=${END_NR_NUM}; ++counter))
         do
-            dir_name=$(cat ./list.lock | awk 'NR=="'${counter}'"{print}')
+            DIR_NAME=$(cat ${SCRIPT_DIR}/list.lock | awk 'NR=="'${counter}'"{print}')
             if [ ${counter} -eq 1 ];then
             # 取回全量备份
                 innobackupex \
                 --decompress \
                 --parallel=4 \
-                ${BAK_PATH}/${recovery_date}/${dir_name} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
-                find  ${BAK_PATH}/${recovery_date}/${dir_name} -name "*.qp" -delete
+                ${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+                find  ${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} -name "*.qp" -delete
                 innobackupex \
                 --apply-log \
                 --redo-only \
                 --use-memory=4G \
-                ${BAK_PATH}/${recovery_date}/${dir_name} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+                ${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
                 # 定义全量备份目录变量
-                full_backup_dir=${BAK_PATH}/${recovery_date}/${dir_name}
-            elif [ ${counter} -eq ${end_line_number} ];then
+                FULL_BACKUP_DIR=${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME}
+            elif [ ${counter} -eq ${END_NR_NUM} ];then
             # 合并最后一个增量，不需要--redo-only参数
                 innobackupex \
                 --decompress \
                 --parallel=4 \
-                ${BAK_PATH}/${recovery_date}/${dir_name} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
-                find ${BAK_PATH}/${recovery_date}/${dir_name} -name "*.qp" -delete
+                ${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+                find ${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} -name "*.qp" -delete
                 innobackupex \
                 --apply-log \
                 --use-memory=4G \
-                ${full_backup_dir} \
-                --incremental-dir=${BAK_PATH}/${recovery_date}/${dir_name} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+                ${FULL_BACKUP_DIR} \
+                --incremental-dir=${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
             else
             # 合并非全量备份和非最后一次的增量备份
                 innobackupex \
                 --decompress \
                 --parallel=4 \
-                ${BAK_PATH}/${recovery_date}/${dir_name} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
-                find ${BAK_PATH}/${recovery_date}/${dir_name} -name "*.qp" -delete
+                ${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+                find ${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} -name "*.qp" -delete
                 innobackupex \
                 --apply-log \
                 --use-memory=4G \
                 --redo-only \
-                ${full_backup_dir} \
-                --incremental-dir=${BAK_PATH}/${recovery_date}/${dir_name} \
+                ${FULL_BACKUP_DIR} \
+                --incremental-dir=${BAK_PATH}/${SUB_BACKUP_DIR}/${DIR_NAME} \
                 >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
             fi
         done
@@ -194,79 +192,119 @@ do_packaging_backup(){
 }
 
 do_recovery(){
-    read -p "输入日期[2018-02-23 17-00-00]: "
-    recovery_time=$REPLY
-    recovery_date=$(echo ${recovery_time} | awk -F '[-," "]' '{print $1$2$3}')
-    recovery_datetime=$(echo ${recovery_time} | awk '{gsub(" ","_"); print $1$2}')
-    do_write_list ${recovery_date}
-    do_merge_backup ${recovery_datetime} ${recovery_date}
+    SUB_BACKUP_DIR=$1
+    RECOVERY_INC_DIR=$2
+    do_merge_backup ${RECOVERY_INC_DIR} ${SUB_BACKUP_DIR}
+    if [ "$?" -eq 0 ];then
+        echo "Merge SUCC"
+    else
+        echo "Merge FAIL"
+        exit 1
+    fi
+    # 关闭mysql服务
     service mysqld stop
-    dir_name=$(cat ${SCRIPT_DIR}/list.lock | awk 'NR==1{print}')
+    # 获取全量备份目录
+    FULL_BACKUP_DIR=$(cat ${SCRIPT_DIR}/list.lock | awk 'NR==1{print}')
+    # 回滚所有未提交的事务
     innobackupex \
     --apply-log \
-    ${BAK_PATH}/${recovery_date}/${dir_name} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+    ${BAK_PATH}/${SUB_BACKUP_DIR}/${FULL_BACKUP_DIR} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+
     if [ $? -eq 0 ];then
-        echo "开始回滚所有未提交的事务" > ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+        echo "开始回滚所有未提交的事务" >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
     else
-        echo -e "开始回滚所有未提交的事务失败，请尝试手动执行命令: \ninnobackupex
-        --apply-log ${BAK_PATH}/${recovery_date}/${dir_name}" >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+        echo -e "开始回滚所有未提交的事务失败，请尝试手动执行命令: \ninnobackupex --apply-log ${BAK_PATH}/${SUB_BACKUP_DIR}/${FULL_BACKUP_DIR}" >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
         exit 1
     fi
 
     if test -d ${DATA_DIR}; then
-        echo -e "${DATA_DIR}目录存在, 在回写时将失败，所以这里选退出了,请手动执行: \ninnobackupex
-        --copy-back ${BAK_PATH}/${recovery_date}/${dir_name}" >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+        echo -e "${DATA_DIR}目录存在, 在回写时会失败，这里先退出，请手动删除数据目录并手动执行: \ninnobackupex --copy-back ${BAK_PATH}/${SUB_BACKUP_DIR}/${FULL_BACKUP_DIR}" >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
         exit 1
     fi
-
+    # 拷回数据至数据目录
     innobackupex \
     --copy-back \
-    ${BAK_PATH}/${recovery_date}/${dir_name} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+    ${BAK_PATH}/${SUB_BACKUP_DIR}/${FULL_BACKUP_DIR} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+
     if [ $? -eq 0 ];then
         chown -R mysql.mysql ${DATA_DIR}
         service mysqld start
-        rm -f ${SCRIPT_DIR}/list.lock
     else
         exit 1
     fi
 }
 
 do_replay_binlog(){
-    read -p "输入时间[比如: 2018-02-23 17-10-10]: " recovery_day recovery_time
-    stop_time=$(echo ${recovery_time} | awk '{gsub("-", ":");print $1$2$3}')
-    sub_backup_dir=$(echo ${recovery_day} | awk -F '-' '{print $1$2$3}')
-    hour=$(echo ${recovery_time} | awk -F '-' '{print $1}')
-    ((next_hour=${hour} + 1))
-    current_inc_string=${recovery_day}_${hour}*
-    next_inc_string=${recovery_day}_${next_hour}*
-    current_inc_dir=$(find ${BAK_PATH}/${sub_backup_dir}/ -name "${current_inc_string}")
+    SUB_BACKUP_DIR=$1
+    STOP_TIME=$2
+    RECOVERY_INC_DIR=$3
+    RECOVERY_NEX_DIR=$4
+    RECOVERY_DAY=$5
+    STOP_DATETIME="${RECOVERY_DAY} ${STOP_TIME}"
 
-    if test -f ${current_inc_dir}/xtrabackup_binlog_info;then
-        begin_file=$(cat ${current_inc_dir}/xtrabackup_binlog_info | awk '{print $1}')
-        begin_position=$(cat ${current_inc_dir}/xtrabackup_binlog_info | awk '{print $2}')
-    else
-        exit 1
-    fi
+    if test -f ${BAK_PATH}/${SUB_BACKUP_DIR}/${RECOVERY_INC_DIR}/xtrabackup_binlog_info; then
+         begin_file=$(cat ${BAK_PATH}/${SUB_BACKUP_DIR}/${RECOVERY_INC_DIR}/xtrabackup_binlog_info | awk '{print $1}')
+         begin_position=$(cat ${BAK_PATH}/${SUB_BACKUP_DIR}/${RECOVERY_INC_DIR}/xtrabackup_binlog_info | awk '{print $2}')
+     else
+         exit 1
+     fi
 
-    next_inc_dir=$(find ${BAK_PATH}/${sub_backup_dir}/ -name "${next_inc_string}")
-    if [ -d ${next_inc_dir} ];then
-        if test -f ${next_inc_dir}/xtrabackup_binlog_info.qp;then
+    if [ ! -z ${RECOVERY_NEX_DIR} ];then
+        if test -f  ${BAK_PATH}/${SUB_BACKUP_DIR}/${RECOVERY_NEX_DIR}/xtrabackup_binlog_info.qp;then
             innobackupex \
             --decompress \
             --parallel=4 \
-            ${next_inc_dir} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
-            find ${BAK_PATH}/${recovery_date}/${dir_name} -name "*.qp" -delete
+            ${BAK_PATH}/${SUB_BACKUP_DIR}/${RECOVERY_NEX_DIR} >> ${LOG_DIR}/recovery_info_${CURRENT_DATE}.log 2>&1
+            find ${BAK_PATH}/${SUB_BACKUP_DIR}/${RECOVERY_NEX_DIR} -name "*.qp" -delete
         fi
-        end_file=$(cat ${next_inc_dir}/xtrabackup_binlog_info | awk '{print $1}')
-
-        mysqlbinlog ${begin_file} ${end_file} \
-        --start-position=${begin_position} \
-        --stop-datetime="${recovery_day} ${stop_time}" | mysql -u root -p${ADMIN_PASS}
+        end_file=$(cat ${BAK_PATH}/${SUB_BACKUP_DIR}/${RECOVERY_NEX_DIR}/xtrabackup_binlog_info | awk '{print $1}')
     else
         end_file=${begin_file}
-        mysqlbinlog ${begin_file} \
-        --start-position=${begin_position} \
-        --stop-datetime="${recovery_day} ${stop_time}" | mysql -u root -p${ADMIN_PASS}
+    fi
+    mysqlbinlog ${BINLOG_DIR}/${begin_file} \
+                ${BINLOG_DIR}/${end_file} \
+                --start-position=${begin_position} \
+                --stop-datetime="${STOP_DATETIME}"| mysql -uroot -p
+
+    if [ "$?" -eq 0 ];then
+        echo "recovery Success"
+    else
+        echo "recovery Failed."
+        exit 1
+    fi
+}
+
+do_recovery_main(){
+    read -p "请准备好数据库管理员密码，后面要用到，这里请输入时间[2018-02-23 17-10-10]: " RECOVERY_DAY RECOVERY_TIME
+    STOP_TIME=$(echo ${RECOVERY_TIME} | awk '{gsub("-", ":");print $1$2$3}')
+    SUB_BACKUP_DIR=$(echo ${RECOVERY_DAY} | awk -F '-' '{print $1$2$3}')
+    RECOVERY_H=$(echo ${RECOVERY_TIME} | awk -F'-' '{print $1}')
+    RECOVERY_M=$(echo ${RECOVERY_TIME} | awk -F'-' '{print $2}')
+    REGEX_STRING=${RECOVERY_DAY}_${RECOVERY_H}-${RECOVERY_M:0:1}[0-9]
+    do_write_list ${SUB_BACKUP_DIR}
+    RECOVERY_INC_DIR=$(cat ${SCRIPT_DIR}/list.lock | awk '/'${REGEX_STRING}'/ {print}')
+    RECOVERY_NEX_DIR=$(cat ${SCRIPT_DIR}/list.lock | awk '/'${REGEX_STRING}'/ {nr[NR+1]; next};NR in nr')
+    do_recovery ${SUB_BACKUP_DIR} ${RECOVERY_INC_DIR}
+    while :
+    do
+        checkPidExists
+        num=$?
+        if [ ${num} -eq 0 ];then
+            break
+        fi
+    done
+
+    do_replay_binlog ${SUB_BACKUP_DIR} ${STOP_TIME} ${RECOVERY_INC_DIR} ${RECOVERY_NEX_DIR} ${RECOVERY_DAY}
+    if [ $? -eq 0 ];then
+        rm -rf ${SCRIPT_DIR}/list.lock
+    fi
+}
+
+checkPidExists() {
+    if [ -z `pidof mysqld` ];then
+        return 1
+    else
+        return 0
     fi
 }
 
@@ -284,10 +322,7 @@ case $1 in
     do_packaging_backup
     ;;
     recovery)
-    do_recovery
-    ;;
-    binlog)
-    do_replay_binlog
+    do_recovery_main
     ;;
     *)
     echo "Usage: $0 <params: [full|inc|recovery|packaging]>"
@@ -299,3 +334,4 @@ case $1 in
     echo
     ;;
 esac
+
